name: Build

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  validate:
    name: Restore Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: WeihanLi/dotnet-install@v0.2.0
        with:
          version: 10.0.x

      - name: Restore
        run: dotnet restore ./weixin-bot-sdk-csharp.slnx

      - name: Test
        run: dotnet test ./Weixin.Bot.Sdk.Test/Weixin.Bot.Sdk.Test.csproj -c Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory ./artifacts/TestResults --collect:"XPlat Code Coverage"

      - name: Build sample project
        run: dotnet build ./Weixin.Bot.Sdk.Sample/Weixin.Bot.Sdk.Sample.csproj -c Release
