name: Build

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  validate:
    name: Restore and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: WeihanLi/dotnet-install@v0.2.0
        with:
          version: 10.0.x

      - name: Build SDK project
        run: dotnet build ./Weixin.Bot.Sdk/Weixin.Bot.Sdk.csproj -c Release

      - name: Build sample project
        run: dotnet build ./Weixin.Bot.Sdk.Sample/Weixin.Bot.Sdk.Sample.csproj -c Release
